# Generated by Django 5.2.6 on 2025-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('musicLocation', models.CharField(max_length=500)),
                ('cover', models.CharField(max_length=500)),
            ],
        ),
    ]
